### ISSUE TITLE
Question on short sequences and 2013 PNAS paper

### ISSUE THREAD

**Issue by jamesdalg** [shay-zakov/BFBFinder#3]
In looking at the 2013 PNAS paper, I notice that in figure 4A, it suggests that the number of false positives is quite high for short sequences (e.g. length 6). The examples given on the site are very short (e.g. length 3, with [4,4,4]). Would you therefore recommend using longer vectors of CNs with the 2015 algorithm ( 10-12, like in figure 4A of the PNAS paper)?

**Comment by shay-zakov** [comment]
Hi James,

Yes, for short count vectors it is more likely that such vectors will look **compatible** with BFB, even if a non-BFB process caused the increment in copy numbers. The longer the count vector is, the less likely that a non-BFB process would produce counts which are compatible with BFB. Therefore, if the algorithm finds compatibility between some long count vector and BFB it should be considered as a stronger evidence for that BFB is the actual process that caused the CN increments.

As for recommending using longer vectors - sure, if you have ones. But note that (a) the effective length is the number of changes between consecutive counts (i.e. the counts [a, b, b, c, c, b] should be regarded as [a, b, c, b] with an effective length of 4), and (b) it is possible that only some sub-interval of the genome underwent BFB, while CN increments outside this interval are due to other processes (in which case the full count vector may not be compatible with BFB while some sub-interval of it is). Also, note that the ploidy of the genome should be considered when estimating the counts. E.g. if assuming a diploid genome in which only one of the two chromosomes underwent BFB, you should reduce 1 from every count due to the non-BFB segment copies.

**Comment by jamesdalg** [comment]
Great answer. Thanks again.
